### ISSUE TITLE
Error on user file loading if volume is not present

### ISSUE THREAD

**Issue by cstefanache** [ascentcore/ml-blocks#54]
having this example:

```
gunter-train:
    image: gunter-train
    container_name: gunter-train
    extends:
      file: ../../../ml-blocks-train/src/app/docker-compose-train-dev.yml
      service: ml-block-train
    volumes:
      - .:/app/user
```

if `volumes` is missing then there will be an error thrown on `plugin_loader.py` when loading source because the array contains a single `[None]`  element
